# Linear Algebra

What is linear algebra? The branch of mathematics that deals with vector spaces. 

In [47]:
import numpy as np

height_weight_age = [70, # inches
                     170, # pounds
                     40] # years
grades = [95, # exam1
          80, # exam2
          75, # exam3 
          62] # exam4

In [48]:
# np.add(v, w)

def vector_add(v, w):
    """adds corresponding elements"""
    return [v_i + w_i for v_i, w_i in zip(v, w)]

In [49]:
# np.subtract(v, w)

def vector_subtract(v, w):
    """subtracts corresponding elements"""
    return [v_i - w_i for v_i, w_i in zip(v, w)]

In [50]:
# np.sum(v)

def vector_sum(vectors):
    """sum all corresponding elements"""
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result

In [51]:
# def vector_sum(vectors):
#     return reduce(vector_add, vectors)

# vector_sum = partial(reduce, vectors_add)

In [52]:
def scalar_multiply(c, v):
    """c is a number, v is a vector"""
    return [c * v_i for v_i in v]

In [53]:
scalar_multiply(5, [1,2,3])

[5, 10, 15]

In [54]:
5 * np.array([1,2,3])

array([ 5, 10, 15])

In [55]:
def vector_mean(vectors):
    """compute the vector whose ith elements is the mean of the ith elements of the input vectors"""
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum(vectors))

In [70]:
vector_mean([[1],[2],[3]])

[2.0]

In [71]:
np.mean([[1],[2],[3]])

2.0

In [57]:
def dot(v, w):
    return sum(v_i * w_i for v_i, w_i in zip(v, w))

In [58]:
def sum_of_squares(v):
    return dot(v, v)

In [59]:
import math

def magnitude(v):
    return math.sqrt(sum_of_squares(v))

In [72]:
def squared_distance(v, w):
    return sum_of_squares(vector_subtract(v, w))

squared_distance([1,2], [3,4])

8

In [79]:
# Distance.
np.sqrt(np.sum(np.square(np.array([1,2]) - np.array([3,4]))))

2.8284271247461903

In [61]:
import numpy as np

# The same as squared distance.
np.linalg.norm(np.array([1,2]) - np.array([3, 4])) ** 2

8.000000000000002

In [62]:
def distance(v, w):
    return math.sqrt(squared_distance(v, w))

## Matrix

A matrix is a two-dimensional collection of numbers.

In [63]:
A = [[1, 2, 3],
     [4, 5, 6]]
B = [[1, 2], 
     [3, 4], 
     [5, 6]]

In [80]:
def shape(A):
    num_rows = len(A)
    num_cols = len(A[0]) if A else 0 # Number of elements in the first row.
    return num_rows, num_cols

In [81]:
np.array(A).shape

(2, 3)

In [82]:
def get_row(A, i):
    return A[i]

In [83]:
np.array(A)[1]

array([4, 5, 6])

In [84]:
def get_column(A, j):
    return [A_i[j] # jth element of row A_i
            for A_i in A] # for each row A_i

In [85]:
np.array(A)[:, 1]

array([2, 5])

In [67]:
def make_matrix(num_rows, num_cols, entry_fn):
    """return the num_rows x num_cols matrix
    whose (i, j)th entry is entry_fn(i, j)"""
    return [[entry_fn(i, j) # Given i, create a list
            for j in range(num_cols)] # [entry_fn(i, 0), ...]
            for i in range(num_rows)] # create one list for each i

In [68]:
def is_diagonal(i, j):
    """1's on the diagonal, 0's everywhere else"""
    return 1 if i == j else 0

In [86]:
identity_matrix = make_matrix(5, 5, is_diagonal)
identity_matrix

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

In [87]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])